// <auto-generated />
using System;
using EmployeePortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeePortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250719210931_Mig1")]
    partial class Mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeePortal.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("EmployeePortal.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            IsActive = false,
                            Name = "Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            IsActive = false,
                            Name = "System Administrator"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            IsActive = false,
                            Name = "Network Engineer"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            IsActive = false,
                            Name = "HR Specialist"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            IsActive = false,
                            Name = "HR Manager"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            IsActive = false,
                            Name = "Talent Acquisition Coordinator"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            IsActive = false,
                            Name = "Sales Executive"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            IsActive = false,
                            Name = "Sales Manager"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 3,
                            IsActive = false,
                            Name = "Account Executive"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 4,
                            IsActive = false,
                            Name = "Office Manager"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 4,
                            IsActive = false,
                            Name = "Executive Assistant"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 4,
                            IsActive = false,
                            Name = "Receptionist"
                        });
                });

            modelBuilder.Entity("EmployeePortal.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 1,
                            Email = "john@example.com",
                            EmployeeTypeId = 1,
                            FullName = "John Doe",
                            Gender = "Male",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 5,
                            Email = "jane@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Jane Smith",
                            Gender = "Female",
                            HireDate = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 80000m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1992, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 7,
                            Email = "sam@example.com",
                            EmployeeTypeId = 3,
                            FullName = "Sam Wilson",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1995, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            DesignationId = 11,
                            Email = "anna@example.com",
                            EmployeeTypeId = 2,
                            FullName = "Anna Taylor",
                            Gender = "Female",
                            HireDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 40000m
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1989, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 3,
                            Email = "tom@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Tom Brown",
                            Gender = "Male",
                            HireDate = new DateTime(2019, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1987, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 4,
                            Email = "emma@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Emma Davis",
                            Gender = "Female",
                            HireDate = new DateTime(2017, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1990, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 8,
                            Email = "luke@example.com",
                            EmployeeTypeId = 3,
                            FullName = "Luke Miller",
                            Gender = "Male",
                            HireDate = new DateTime(2020, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 85000m
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1993, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            DesignationId = 10,
                            Email = "olivia@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Olivia Johnson",
                            Gender = "Female",
                            HireDate = new DateTime(2021, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1997, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 2,
                            Email = "mia@example.com",
                            EmployeeTypeId = 4,
                            FullName = "Mia Moore",
                            Gender = "Female",
                            HireDate = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 30000m
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1986, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 6,
                            Email = "chris@example.com",
                            EmployeeTypeId = 2,
                            FullName = "Chris Evans",
                            Gender = "Other",
                            HireDate = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1994, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 7,
                            Email = "sophia@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Sophia White",
                            Gender = "Female",
                            HireDate = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 52000m
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1996, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            DesignationId = 12,
                            Email = "liam@example.com",
                            EmployeeTypeId = 2,
                            FullName = "Liam Green",
                            Gender = "Male",
                            HireDate = new DateTime(2020, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 38000m
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1991, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 2,
                            Email = "noah@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Noah Black",
                            Gender = "Male",
                            HireDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1988, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            DesignationId = 4,
                            Email = "isabella@example.com",
                            EmployeeTypeId = 1,
                            FullName = "Isabella Blue",
                            Gender = "Female",
                            HireDate = new DateTime(2017, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 76000m
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1993, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            DesignationId = 9,
                            Email = "james@example.com",
                            EmployeeTypeId = 3,
                            FullName = "James Brown",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 62000m
                        });
                });

            modelBuilder.Entity("EmployeePortal.Models.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            Name = "Permanent"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Temporary"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Contract"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Intern"
                        });
                });

            modelBuilder.Entity("EmployeePortal.Models.Designation", b =>
                {
                    b.HasOne("EmployeePortal.Models.Department", "Department")
                        .WithMany("Designations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeePortal.Models.Employee", b =>
                {
                    b.HasOne("EmployeePortal.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeePortal.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeePortal.Models.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("EmployeePortal.Models.Department", b =>
                {
                    b.Navigation("Designations");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EmployeePortal.Models.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
